namespace Auth.Application.DTOs;

/// <summary>
/// Activity generated by one application inside the window.
/// A null application collects rows carrying no application context.
/// </summary>
public class ApplicationActivityDto
{
    public Guid? ApplicationId { get; set; }
    public string? ApplicationName { get; set; }
    public bool IsActive { get; set; }
    public int SuccessfulLogins { get; set; }
    public int DistinctUsers { get; set; }
    public int ActiveSessions { get; set; }
}

/// <summary>
/// One organization's enablement of one application.
/// </summary>
public class OrganizationApplicationEnablementDto
{
    public Guid OrganizationId { get; set; }
    public string OrganizationName { get; set; } = string.Empty;
    public Guid ApplicationId { get; set; }
    public string ApplicationName { get; set; } = string.Empty;
    public string? SubscriptionTier { get; set; }
    public DateTime? ExpiresAt { get; set; }
}

/// <summary>
/// Dashboard per-application activity and organization/application enablement.
/// </summary>
public class AppActivityDto
{
    public int Days { get; set; }
    public List<ApplicationActivityDto> Applications { get; set; } = [];
    public List<OrganizationApplicationEnablementDto> OrganizationApplications { get; set; } = [];
}
