<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Middleware\" />
    <Folder Include="Modules\ApiKeyManagement\Controllers\" />
    <Folder Include="Modules\ApiKeyManagement\Services\" />
    <Folder Include="Modules\AuditLog\Controllers\" />
    <Folder Include="Modules\AuditLog\EventHandlers\" />
    <Folder Include="Modules\AuditLog\Services\" />
    <Folder Include="Modules\Authentication\Controllers\" />
    <Folder Include="Modules\Authentication\Commands\" />
    <Folder Include="Modules\Authentication\Events\" />
    <Folder Include="Modules\Authentication\Services\" />
    <Folder Include="Modules\PermissionManagement\Controllers\" />
    <Folder Include="Modules\PermissionManagement\Services\" />
    <Folder Include="Modules\RoleManagement\Controllers\" />
    <Folder Include="Modules\RoleManagement\Services\" />
    <Folder Include="Modules\UserManagement\Controllers\" />
    <Folder Include="Modules\UserManagement\Commands\" />
    <Folder Include="Modules\UserManagement\Events\" />
    <Folder Include="Modules\UserManagement\Services\" />
  </ItemGroup>

</Project>
