-- Admin User Seed Data
-- Creates the initial super admin user
-- NOTE: Password hash is a placeholder - must be updated with real Argon2id hash!

DECLARE @SystemUserId UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000001';
DECLARE @AdminUserId UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000002';
DECLARE @SuperAdminRoleId UNIQUEIDENTIFIER = '10000000-0000-0000-0000-000000000001';
DECLARE @UserRoleId UNIQUEIDENTIFIER = '10000000-0000-0000-0000-000000000005';

-- Create system user (used for seeding and system operations)
IF NOT EXISTS (SELECT 1 FROM [dbo].[Users] WHERE [Id] = @SystemUserId)
BEGIN
    INSERT INTO [dbo].[Users]
    (
        [Id],
        [Username],
        [Email],
        [NormalizedEmail],
        [PasswordHash],
        [FirstName],
        [LastName],
        [PreferredLanguage],
        [TimeZone],
        [IsEmailConfirmed],
        [Status],
        [CreatedAt],
        [CreatedBy]
    )
    VALUES
    (
        @SystemUserId,
        N'system',
        N'system@localhost',
        N'SYSTEM@LOCALHOST',
        N'$argon2id$v=19$m=65536,t=3,p=4$AAAAAAAAAAAAAAAAAAAAAA$AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',  -- Placeholder - cannot login
        N'System',
        N'Account',
        N'en',
        N'UTC',
        1,  -- Email confirmed
        2,  -- Status: Inactive (cannot login)
        GETUTCDATE(),
        @SystemUserId
    );
    PRINT 'Created system user';
END

-- Create admin user
-- DEFAULT PASSWORD: Admin@123! (MUST be changed on first login!)
-- Hash generated with Argon2id: m=65536,t=3,p=4
IF NOT EXISTS (SELECT 1 FROM [dbo].[Users] WHERE [Id] = @AdminUserId)
BEGIN
    INSERT INTO [dbo].[Users]
    (
        [Id],
        [Username],
        [Email],
        [NormalizedEmail],
        [PasswordHash],
        [FirstName],
        [LastName],
        [PreferredLanguage],
        [TimeZone],
        [IsEmailConfirmed],
        [Status],
        [MustChangePassword],
        [CreatedAt],
        [CreatedBy]
    )
    VALUES
    (
        @AdminUserId,
        N'admin',
        N'admin@company.com',
        N'ADMIN@COMPANY.COM',
        -- This is a placeholder hash - the actual hash must be generated by the application
        -- The application should update this on first run or provide a setup wizard
        N'$argon2id$v=19$m=65536,t=3,p=4$c2FsdHNhbHRzYWx0c2FsdA$PLACEHOLDER_HASH_UPDATE_ON_FIRST_RUN',
        N'System',
        N'Administrator',
        N'en',
        N'UTC',
        1,  -- Email confirmed
        1,  -- Status: Active
        1,  -- Must change password on first login
        GETUTCDATE(),
        @SystemUserId
    );
    PRINT 'Created admin user (password must be set via application)';
END

-- Assign Super Admin role to admin user
IF NOT EXISTS (SELECT 1 FROM [dbo].[UserRoles] WHERE [UserId] = @AdminUserId AND [RoleId] = @SuperAdminRoleId)
BEGIN
    INSERT INTO [dbo].[UserRoles]
    (
        [UserId],
        [RoleId],
        [ApplicationId],
        [AssignedAt],
        [AssignedBy],
        [IsActive]
    )
    VALUES
    (
        @AdminUserId,
        @SuperAdminRoleId,
        NULL,  -- Global role (all applications)
        GETUTCDATE(),
        @SystemUserId,
        1
    );
    PRINT 'Assigned Super Admin role to admin user';
END

-- Also assign User role (for profile access)
IF NOT EXISTS (SELECT 1 FROM [dbo].[UserRoles] WHERE [UserId] = @AdminUserId AND [RoleId] = @UserRoleId)
BEGIN
    INSERT INTO [dbo].[UserRoles]
    (
        [UserId],
        [RoleId],
        [ApplicationId],
        [AssignedAt],
        [AssignedBy],
        [IsActive]
    )
    VALUES
    (
        @AdminUserId,
        @UserRoleId,
        NULL,  -- Global role
        GETUTCDATE(),
        @SystemUserId,
        1
    );
    PRINT 'Assigned User role to admin user';
END

PRINT 'Admin user setup complete';
PRINT 'IMPORTANT: Update the admin password hash using the application before production deployment!';
GO
