<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Application\EventHandlers\" />
    <Folder Include="Application\Abstractions\" />
    <Folder Include="Application\Mappings\" />
    <Folder Include="Application\Behaviors\" />
    <Folder Include="Application\Services\" />
    <Folder Include="Application\UseCases\ApiKeys\" />
    <Folder Include="Application\UseCases\Applications\" />
    <Folder Include="Application\UseCases\Authentication\Commands\" />
    <Folder Include="Application\UseCases\Authentication\Queries\" />
    <Folder Include="Application\UseCases\Permissions\" />
    <Folder Include="Application\UseCases\Roles\" />
    <Folder Include="Application\UseCases\Users\" />
    <Folder Include="Contracts\Responses\" />
    <Folder Include="Contracts\Requests\" />
    <Folder Include="Domain\Entities\" />
    <Folder Include="Domain\Events\" />
    <Folder Include="Domain\Exceptions\" />
    <Folder Include="Domain\Enums\" />
    <Folder Include="Domain\Interfaces\Repositories\" />
    <Folder Include="Domain\ValueObjects\" />
    <Folder Include="Foundation\Base\" />
    <Folder Include="Foundation\Interfaces\" />
    <Folder Include="Infrastructure\Authentication\" />
    <Folder Include="Infrastructure\Authorization\" />
    <Folder Include="Infrastructure\Caching\" />
    <Folder Include="Infrastructure\Data\" />
    <Folder Include="Infrastructure\External\" />
    <Folder Include="DTOs\" />
    <Folder Include="Constants\" />
    <Folder Include="Enums\" />
    <Folder Include="Configuration\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
