namespace Auth.Domain.ReadModels.Dashboard;

/// <summary>
/// Activity generated by one application inside the window.
/// A null application collects rows that carried no application context.
/// </summary>
public sealed record ApplicationActivity(
    Guid? ApplicationId,
    string? ApplicationName,
    bool IsActive,
    int SuccessfulLogins,
    int DistinctUsers,
    int ActiveSessions);

/// <summary>
/// One organization's enablement of one application.
/// </summary>
public sealed record OrganizationApplicationEnablement(
    Guid OrganizationId,
    string OrganizationName,
    Guid ApplicationId,
    string ApplicationName,
    string? SubscriptionTier,
    DateTime? ExpiresAt);

/// <summary>
/// Aggregated per-application activity and organization/application enablement.
/// </summary>
public sealed record AppActivitySnapshot
{
    /// <summary>Per-application activity inside the window (successful logins, distinct users, active sessions).</summary>
    public required IReadOnlyList<ApplicationActivity> Applications { get; init; }

    /// <summary>Active organization/application enablements with subscription tier and expiry.</summary>
    public required IReadOnlyList<OrganizationApplicationEnablement> OrganizationApplications { get; init; }
}
