using System.Reflection;
using Auth.Application.DTOs;

namespace Auth_API.Tests.OrganizationManagement;

/// <summary>
/// An invitation token may exist in the invited mailbox and nowhere a caller can
/// reach.
/// </summary>
/// <remarks>
/// Registering through an invitation confirms the new account's address with no
/// further proof, on the grounds that the token was delivered to that mailbox.
/// The reasoning is sound; the premise was not. <c>OrganizationInvitationDto</c>
/// carried the plaintext back to whoever created the invitation, and both the
/// invite and the resend endpoints returned it under a permission every
/// organization owner holds. The chain that made of it: any signed-in user creates
/// an organization (no permission required), invites any address, reads the token
/// out of their own response, and registers that address with the email
/// pre-confirmed and a password of their choosing — while the console showed both
/// registration doors closed.
///
/// <para>
/// These assertions are deliberately about the TYPE rather than about a handler
/// call. A per-case assertion says "this path does not leak the token today"; the
/// type says "no path can", which is what a security boundary has to mean. The
/// same reason the property was deleted instead of merely left unassigned.
/// </para>
/// </remarks>
public class InvitationResponseGuardTests
{
    /// <summary>
    /// Names a reader would reach for if they re-added the field. Matching is
    /// case-insensitive and by substring, so <c>Token</c>, <c>InvitationToken</c>
    /// and <c>PlainToken</c> all trip it.
    /// </summary>
    private static readonly string[] ForbiddenFragments = ["token", "secret", "plaintext"];

    [Fact]
    public void InvitationDto_CarriesNoToken()
    {
        var offenders = PublicProperties<OrganizationInvitationDto>()
            .Where(NamesACredential)
            .Select(p => p.Name)
            .ToList();

        offenders.Should().BeEmpty(
            "redeeming an invitation token confirms an email address with no further proof, so the "
            + "plaintext may exist only in the mailbox it was sent to — a property here is returned "
            + "to the inviter, who is exactly the party the confirmation is supposed to exclude");
    }

    /// <summary>
    /// The preview is served anonymously to whoever holds a token, so it must not
    /// hand back the token that fetched it — nor anything else a caller could
    /// redeem or replay.
    /// </summary>
    [Fact]
    public void InvitationPreview_CarriesNoToken()
    {
        PublicProperties<InvitationPreviewDto>()
            .Where(NamesACredential)
            .Select(p => p.Name)
            .Should().BeEmpty("the preview endpoint is anonymous");
    }

    [Fact]
    public void InvitationAcceptResult_CarriesNoToken()
    {
        PublicProperties<InvitationAcceptResultDto>()
            .Where(NamesACredential)
            .Select(p => p.Name)
            .Should().BeEmpty("acceptance returns an outcome, not a credential");
    }

    /// <summary>
    /// The other half of the rule, asserted where it is easy to break silently:
    /// the token must still reach the invitee. A handler that stopped returning
    /// the plaintext AND stopped mailing it would pass every assertion above while
    /// making invitations unusable.
    /// </summary>
    [Fact]
    public void BothInvitationHandlers_StillMailTheToken()
    {
        foreach (var handler in new[] { "InviteMember", "ResendInvitation" })
        {
            var source = File.ReadAllText(Path.Combine(
                SolutionDirectory(), "Auth.Application", "Features", "Organizations",
                handler, $"{handler}CommandHandler.cs"));

            source.Should().Contain("[\"InvitationToken\"]",
                "{0} must still deliver the plaintext to the invited mailbox", handler);
            source.Should().Contain("RecipientAddress = invitation.Email",
                "{0} must address that mail to the invitee and to nobody else", handler);
        }
    }

    /// <summary>
    /// The generated TypeScript client is regenerated from the API's OpenAPI
    /// document, so a field that reappears in C# reappears there. Asserting it
    /// here keeps the two from drifting when the client is regenerated by hand.
    /// </summary>
    [Fact]
    public void TheGeneratedClient_HasNoInvitationToken()
    {
        var schema = File.ReadAllText(Path.Combine(
            RepositoryRoot(), "Auth_UI", "packages", "api", "src", "schema.d.ts"));

        var from = schema.IndexOf("OrganizationInvitationDto: {", StringComparison.Ordinal);
        from.Should().BeGreaterThan(-1, "the DTO must still be part of the published contract");

        var to = schema.IndexOf("};", from, StringComparison.Ordinal);
        schema[from..to].Should().NotContain("token",
            "a token on the wire is a token in every client that reads the response");
    }

    #region Helpers

    private static IEnumerable<PropertyInfo> PublicProperties<T>() =>
        typeof(T).GetProperties(BindingFlags.Public | BindingFlags.Instance);

    private static bool NamesACredential(PropertyInfo property) =>
        ForbiddenFragments.Any(fragment =>
            property.Name.Contains(fragment, StringComparison.OrdinalIgnoreCase));

    private static string SolutionDirectory()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "Auth.sln")))
        {
            directory = directory.Parent;
        }

        directory.Should().NotBeNull("the tests must be able to find Auth.sln above their output folder");
        return directory!.FullName;
    }

    private static string RepositoryRoot() => Directory.GetParent(SolutionDirectory())!.FullName;

    #endregion
}
